name: Run Recurring Venmo
on:
  schedule:
    - cron: "0 10 10 * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    name: run recurring venmo
    steps:
      - name: Checkout
        uses: actions/checkout@v3